apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doron-app
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: 'https://github.com/drdrn2510/ArgoCD.git'
    targetRevision: HEAD
    # Points to the folder where your single YAML file lives
    path: helm 
    # REMOVED: The entire helm/valueFiles block is gone
  destination:
    server: 'https://default.svc'
    namespace: default 
  syncPolicy:
    automated:
      prune: true     
      selfHeal: true
